version: "3"

services:

  wpmongo:
    container_name: webprotege-mongodb
    image: mongo:4.1-bionic
    restart: unless-stopped
    volumes: 
      - ./.protegedata/mongodb:/data/db

  neo4j:
    container_name: neo4j
    image: neo4j:4.4.12
    ports:
      - '7474:7474'
    #  - '7473:7473'
      - '7687:7687'
    volumes:
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs
      - ./.neo4j/import:/import
      - ./.neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4JLABS_PLUGINS: '["n10s"]'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32G

  webprotege:
    container_name: webprotege
    image: webprotege-export-neo4j
    depends_on:
      - wpmongo
    restart: unless-stopped
    environment:
      - webprotege.mongodb.host=wpmongo
    volumes: 
    - ./.protegedata/protege:/srv/webprotege
    ports:
      - 5000:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32G

