version: "3"

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093 # change EXTERNAL from localhost to a domain, if necessary
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  wpmongo:
    container_name: webprotege-mongodb
    image: mongo:4.1-bionic
    restart: unless-stopped
    volumes: 
      - ./.protegedata/mongodb:/data/db

  neo4j:
    container_name: neo4j
    image: neo4j:4.4.12
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs
      - ./.neo4j/import:/import
      - ./.neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4JLABS_PLUGINS: '["n10s"]'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32G

  webprotege:
    container_name: webprotege
    image: webprotege-export-neo4j
    depends_on:
      - wpmongo
    restart: unless-stopped
    environment:
      - webprotege.mongodb.host=wpmongo
    volumes: 
    - ./.protegedata/protege:/srv/webprotege
    ports:
      - 5000:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32G

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
